### ISSUE TITLE
Communication server

### ISSUE THREAD

**Issue by mudkipium** [mudkipium/crypto-final-project#1]
Write a server for communication between the victim and the ransomer. This should be basic and not include any encryption/decryption logic yet, since we literally have no code. Maybe something like, the victim's machine opens the communication system and says "Hello, world!" and when the ransomer's machine receives it, replies, "Hello!" back.

**Comment by wsun19** [comment]
Flask? http://flask.pocoo.org/docs/0.12/quickstart/

**Comment by wsun19** [comment]
https://github.com/mudkipium/crypto-final-project/commit/70df1f6ea0d080653ec387bbf61d1fe27e3158ac
